"""
Callback route coverage test.

This test verifies that ALL callback patterns used in the event creation
flow are properly registered in main.py. It catches bugs like:
- Missing route registrations (event_final_yes was never routed)
- Wrong regex patterns (event_time_manual_ vs event_time_manual)
- Silent fallthrough where callbacks match no handler

Run with: python -m tests.test_route_coverage
"""

import re
import sys
import os

# Add project root to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))


# ---------------------------------------------------------------------------
# Patterns that are GENERATED by keyboard builders or CHECKED in handlers
# ---------------------------------------------------------------------------

# These are the callback patterns that the handler code expects to receive.
# Each tuple is (pattern_prefix, is_exact_match, description)

# Patterns that MUST be registered (used in keyboards and checked in handlers)
# Format: (pattern, is_exact_match, description)
PUBLIC_HANDLER_PATTERNS = [
    # Edit/back navigation
    ("event_edit_", False, "edit_previous buttons"),
    ("event_back_to_type", True, "back to type button"),
    ("event_back_to_time_window", True, "back to time_window button"),
    ("event_back_to_transport", True, "back to transport button"),
    # Type selection
    ("event_type_", False, "event type buttons"),
    # Date selection
    ("event_date_preset_", False, "date preset buttons"),
    ("event_date_pick_", False, "date pick buttons"),
    ("event_cal_", False, "calendar navigation (covers cal_ignore, cal_day, cal_nav)"),
    # Time selection
    ("event_time_window_", False, "time window buttons"),
    ("event_time_manual", True, "manual time entry button"),
    ("event_time_option_", False, "time option buttons"),
    # Participants
    ("event_min_", False, "min participants buttons"),
    ("event_target_", False, "target participants buttons"),
    ("event_threshold_", False, "threshold buttons"),
    # Flow continuation
    ("event_duration_", False, "duration buttons"),
    ("event_location_", False, "location buttons"),
    ("event_budget_", False, "budget buttons"),
    ("event_transport_", False, "transport buttons"),
    # Invitees
    ("event_invite_all", True, "invite all button"),
    ("event_invite_custom", True, "invite custom button"),
    # Final confirmation
    ("event_final_yes", True, "confirm button"),
    ("event_final_edit", True, "modify button"),
    ("event_cancel_no", True, "cancel/discard button"),
]

PRIVATE_HANDLER_PATTERNS = [
    (p[: p.index("_") + 1] + "private_" + p[p.index("_") + 1 :], exact, desc)
    for p, exact, desc in PUBLIC_HANDLER_PATTERNS
    if "event_" in p
]

# Rebuild private patterns properly
PRIVATE_HANDLER_PATTERNS = [
    ("private_event_edit_", False, "edit_previous buttons"),
    ("private_event_back_to_type", True, "back to type button"),
    ("private_event_back_to_time_window", True, "back to time_window button"),
    ("private_event_back_to_transport", True, "back to transport button"),
    ("private_event_type_", False, "event type buttons"),
    ("private_event_date_preset_", False, "date preset buttons"),
    ("private_event_date_pick_", False, "date pick buttons"),
    (
        "private_event_cal_",
        False,
        "calendar navigation (covers cal_ignore, cal_day, cal_nav)",
    ),
    ("private_event_time_window_", False, "time window buttons"),
    ("private_event_time_manual", True, "manual time entry button"),
    ("private_event_time_option_", False, "time option buttons"),
    ("private_event_min_", False, "min participants buttons"),
    ("private_event_target_", False, "target participants buttons"),
    ("private_event_threshold_", False, "threshold buttons"),
    ("private_event_duration_", False, "duration buttons"),
    ("private_event_location_", False, "location buttons"),
    ("private_event_budget_", False, "budget buttons"),
    ("private_event_transport_", False, "transport buttons"),
    ("private_event_invite_all", True, "invite all button"),
    ("private_event_invite_custom", True, "invite custom button"),
    ("private_event_final_yes", True, "confirm button"),
    ("private_event_final_edit", True, "modify button"),
    ("private_event_cancel_no", True, "cancel/discard button"),
]


# ---------------------------------------------------------------------------
# Extract registered patterns from main.py
# ---------------------------------------------------------------------------


def extract_registered_patterns(filepath: str) -> dict[str, list[str]]:
    """Extract all callback regex patterns from main.py."""
    with open(filepath) as f:
        content = f.read()

    public_patterns = []
    private_patterns = []

    # Match patterns like: (r"^event_type_", event_creation.handle_callback),
    pattern = re.compile(
        r'\(r"([^"]+)",\s*(event_creation\.(?:handle|private_handle)_callback)\)',
    )

    for match in pattern.finditer(content):
        regex = match.group(1)
        handler = match.group(2)
        if "private_handle" in handler:
            private_patterns.append(regex)
        else:
            public_patterns.append(regex)

    return {"public": public_patterns, "private": private_patterns}


# ---------------------------------------------------------------------------
# Test logic
# ---------------------------------------------------------------------------


def pattern_matches_callback(regex: str, callback_data: str) -> bool:
    """Check if a regex pattern matches a callback data string."""
    return re.match(regex, callback_data) is not None


def is_covered(
    pattern: str, is_exact: bool, registered: list[str], prefix: str
) -> bool:
    """Check if a handler pattern is covered by registered routes."""
    # Generate test callback data that the handler would check
    if is_exact:
        # For exact matches, test if the pattern itself matches any registered route
        if any(pattern_matches_callback(r, pattern) for r in registered):
            return True
        # Also check if a broader pattern covers it (e.g., event_cal_ignore covered by event_calendar_)
        # Extract the base prefix and check if a broader pattern exists
        parts = pattern.split("_", 2)
        if len(parts) >= 3:
            broader = f"{parts[0]}_{parts[1]}_"
            if any(
                pattern_matches_callback(r, broader + "anything") for r in registered
            ):
                return True
        return False
    else:
        # For prefix matches, generate test callbacks that match the prefix
        test_callbacks = [
            pattern + "test1",
            pattern + "test2",
            pattern + "_something",
        ]
        for cb in test_callbacks:
            if any(pattern_matches_callback(r, cb) for r in registered):
                return True
        return False


def test_callback_route_coverage() -> list[str]:
    """Verify all handler callback patterns are registered in main.py."""
    results: list[str] = []
    errors: list[str] = []

    main_py = os.path.join(os.path.dirname(__file__), "..", "main.py")
    registered = extract_registered_patterns(main_py)

    # Test public patterns
    results.append("=== Public Event Creation Patterns ===")
    for pattern, is_exact, description in PUBLIC_HANDLER_PATTERNS:
        covered = is_covered(pattern, is_exact, registered["public"], "event_")
        status = "OK" if covered else "MISSING"
        if not covered:
            errors.append(f"  MISSING: {pattern} ({description})")
        results.append(f"  [{status}] {pattern} -> {description}")

    # Test private patterns
    results.append("\n=== Private Event Creation Patterns ===")
    for pattern, is_exact, description in PRIVATE_HANDLER_PATTERNS:
        covered = is_covered(pattern, is_exact, registered["private"], "private_event_")
        status = "OK" if covered else "MISSING"
        if not covered:
            errors.append(f"  MISSING: {pattern} ({description})")
        results.append(f"  [{status}] {pattern} -> {description}")

    # Summary
    results.append("\n=== Summary ===")
    if errors:
        results.append(f"FAIL: {len(errors)} missing patterns:")
        results.extend(errors)
    else:
        results.append("PASS: All callback patterns are properly registered")

    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    print("=" * 60)
    print("Callback Route Coverage Test")
    print("=" * 60)
    print()

    results = test_callback_route_coverage()
    for r in results:
        print(r)

    print()
    print("=" * 60)

    has_errors = any("MISSING" in r for r in results)
    if has_errors:
        print("RESULT: FAIL - Some callback patterns are not registered")
        print("=" * 60)
        sys.exit(1)
    else:
        print("RESULT: PASS - All callback patterns are registered")
        print("=" * 60)
        sys.exit(0)


if __name__ == "__main__":
    main()
